name: gaia

on:  # yamllint disable-line rule:truthy
  - push

jobs:

  test:
    container:
      image: python:3.9
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint and Test code
        run: |
          curl -sSL https://install.python-poetry.org | python3 - --preview
          export PATH="/github/home/.local/bin:$PATH"
          poetry --version
          poetry install
          poetry run ./lint.sh
          poetry run ./test.sh
